version: '3.9'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

  qr_app:
    build: .
    container_name: qr-web
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/restaurant
      - PORT=3000
    depends_on:
      - mongo
    restart: unless-stopped
