name: CI - Docker Compose Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name:  Build containers
        run: docker compose build

      - name:  Start the server
        run: docker compose up -d

      - name:  Wait for service
        run: sleep 10

      - name:  Test app is up
        run: curl --fail http://localhost:3000 || (echo "App failed to respond!" && exit 1)

      - name:  Cleanup
        run: docker compose down
